const CREATE_IDEA = "CREATE_IDEA";
const SELECT_IDEA = "SELECT_IDEA";
const RANDOM_SELECT_IDEA = "RANDOM_SELECT_IDEA";
const EDIT_IDEA = "EDIT_IDEA";
const COMMIT_EDIT_IDEA = "COMMIT_EDIT_IDEA";
const DELETE_IDEA = "DELETE_IDEA";
const TOGGLE_TASK_OPTIONS_DRAWER = "TOGGLE_TASK_OPTIONS_DRAWER";
const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";
const TOGGLE_IS_LOADING = "TOGGLE_IS_LOADING";
const FETCH_IDEAS = "FETCH_IDEAS";
const FETCH_IDEAS_SUCCESS = "FETCH_IDEAS_SUCCESS";
const FETCH_IDEAS_FAILURE = "FETCH_IDEAS_FAILURE";

export {
  CREATE_IDEA,
  SELECT_IDEA,
  RANDOM_SELECT_IDEA,
  EDIT_IDEA,
  COMMIT_EDIT_IDEA,
  DELETE_IDEA,
  TOGGLE_TASK_OPTIONS_DRAWER,
  TOGGLE_EDIT_MODE,
  TOGGLE_IS_LOADING,
  FETCH_IDEAS,
  FETCH_IDEAS_SUCCESS,
  FETCH_IDEAS_FAILURE,
};
