const CREATE_IDEA = "CREATE_IDEA";
const SELECT_IDEA = "SELECT_IDEA";
const RANDOM_SELECT_IDEA = "RANDOM_SELECT_IDEA";
const EDIT_IDEA = "EDIT_IDEA";
const COMMIT_EDIT_IDEA = "COMMIT_EDIT_IDEA";
const DELETE_IDEA = "DELETE_IDEA";
const TOGGLE_TASK_OPTIONS_DRAWER = "TOGGLE_TASK_OPTIONS_DRAWER";
const TOGGLE_EDIT_MODE = "TOGGLE_EDIT_MODE";

export {
  CREATE_IDEA,
  SELECT_IDEA,
  RANDOM_SELECT_IDEA,
  EDIT_IDEA,
  COMMIT_EDIT_IDEA,
  DELETE_IDEA,
  TOGGLE_TASK_OPTIONS_DRAWER,
  TOGGLE_EDIT_MODE,
};
